### ISSUE TITLE
[User Story]: Create bank account : Bank SMART Contract

### ISSUE THREAD

**Issue by farrellh1** [globe-and-citizen/cnc-portal#119]
**As A** company owner
**I want to** create a bank Account to my company
**When i** create a company bank Account 
**I can** operate transactions with it.

- [x] Create Bank Smart Contract that can store a team's bank account
- [ ] Create view for creating team's bank account
- [ ] Create endpoint to create bank account

**Comment by hermannleboss** [comment]
@farrellh1 For this feature we will create a bank Smart contract for a Team
