### ISSUE TITLE
ux: Team management need somes imrpovement

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#166]
## Description

When you want to delete a team member the owner need to accept before. It's dangerous to be able to delete a team member in one click. The should be an action for confirmation. 

When you try to delete the team owner. You need to have a toast that say you can't remove the owner.

## Acceptance Criteria

- [x] Validation before remove team member
- [x] Toast when you can't remove the team owner.
- [x] Better if you can do this validation in the frontend. You already have the team owner in the team object. So you can check in the team member and hide delete button for team owner.

![image](https://github.com/globe-and-citizen/cnc-portal/assets/28951070/16e7c1ee-24a4-448d-88cb-fce0dfae1f64)

**Comment by dasarathg68** [comment]
"When you try to delete the team owner. You need to have a toast that say you can't remove the owner."
This is present already, just need to refactor it to use the new toast system

**Comment by hermannleboss** [comment]
Yes, but i think it's better to disable remove action where it's the owner.
