### ISSUE TITLE
Update user is not working

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#215]
## Description
![image](https://github.com/globe-and-citizen/cnc-portal/assets/28951070/3a73df05-1fb6-4136-8fcc-672a7b8248c4)

**Comment by hermannleboss** [comment]
It seams like it's not working when you just create an account

**Comment by dasarathg68** [comment]
> It seams like it's not working when you just create an account

This is already fixed by #210. The issue was that the endpoint was not reactive. I have fixed it already, please make sure to pull changes to your branch.
