### ISSUE TITLE
[Feature]: Team and Bank View Panels for Bank Accounts, Teams, & Transactions Management

### ISSUE THREAD

**Issue by farrellh1** [globe-and-citizen/cnc-portal#218]
## Description

**Is your feature request related to a problem? Please describe.**
Sometimes a team want to see the transactions history that happen in the bank smart contract

**Describe the solution you'd like**
Create transactions history of bank smart contract in single team view page

```[tasklist]
### Tasks
- [ ] #227 
- [ ] #226 
```

**Comment by hermannleboss** [comment]
@farrellh1 i've just update the description to add user stories.

**Comment by dasarathg68** [comment]
Fixed by #224.
