### ISSUE TITLE
[Refactor] Folder structure : Refactor the code base to apply the new folder structure

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#288]
## Description

We need to apply the new folder structure so we can have a code base more structured

Here is an example of how we can structure our components:
  Idea of structure
```
  src/
  ├── components/
  │   ├── ui/
  │   │   ├── Button.vue
  │   │   ├── Modal.vue
  │   ├── form/
  │   │   ├── InputField.vue
  │   │   ├── FormGroup.vue
  │   ├── sections/
  │   │   ├── [page-name]/[secton-name].vue
```

In components, we can have a structure like this:
Secion: they are the main part of a page, usualy section are not thinked to be reusable, their main goal is to split the page into small peace of content. Section are grouped into page folder. So we can identify the page and the section of the page.
Sections are component that are alowed to have logic inside. So they can process data like fetching, using composable or accessing the store.

UI: They are the most reusable component, they are the basic component like button, input, modal, etc.
And we can create a folder for each type of component, like Form, Icons etc.

## Acceptance Criteria

Each Page has his section folder
```[tasklist]
### Tasks
- [x] Team View
- [x] Single Team View
- [x] Transactions
```

**Comment by dasarathg68** [comment]
@farrellh1 can you refactor the TransactionsView portion?

**Comment by farrellh1** [comment]
Yes, i will work on it based on priority @dasarathg68
