### ISSUE TITLE
[Search (Side Project)] Governor Contract

### ISSUE THREAD

**Issue by dasarathg68** [globe-and-citizen/cnc-portal#299]
## Description

Tokenize Voting system using ERC 20

## Acceptance Criteria

- [ ] Demo of Voting system using ERC 20

**Comment by hermannleboss** [comment]
@dasarathg68 it seems that you close this issue.
Is it done ?

**Comment by dasarathg68** [comment]
> @dasarathg68 it seems that you close this issue. Is it done ?

Ah no. I have halted this work for now. I will reopen soon once September goal is done.

**Comment by hermannleboss** [comment]
I will move it to specification done and set tag blocked
right ?

**Comment by dasarathg68** [comment]
> I will move it to specification done and set tag blocked right ?

Yes okay
