### ISSUE TITLE
[Feature] Code Quality: Enforce typescript lint rules to have a better code quality

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#325]
## Description

Enable some's code quality rules so we have a better typing.

https://www.learningtypescript.com/articles/why-typescript-doesnt-follow-strict-semantic-versioning

The @typescript-eslint/no-explicit-any lint rule can enforce against explicitly writing any types in code.

The @typescript-eslint/ban-ts-comment lint rule can enforce against comment directives, or enforce that they be accompanied by an explanatory comment.
The @typescript-eslint/prefer-ts-expect-error lint rule can enforce using // @ts-expect-error over // @ts-ignore.

## Acceptance Criteria

- [ ] No any
- [ ] ban ts comment

**Comment by hermannleboss** [comment]
@dasarathg68 i saw you PR on this. 

I will create a new one that enforce the rule so it will check it on your PR

**Comment by dasarathg68** [comment]
> @dasarathg68 i saw you PR on this.
> 
> I will create a new one that enforce the rule so it will check it on your PR

Let's not enforce it strictly for now, there are over 100 instances of explicit any declarations and all checks would keep failing in the pipeline till we fix it.

**Comment by dasarathg68** [comment]
#330

**Comment by hermannleboss** [comment]
I was thinking to open a PR, then everyone responsible of his part will create a PR to the branch and we will finish like that.
