### ISSUE TITLE
I can't approve an action i've revoked the approval

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#375]
## Description

**Describe the bug**
I can't approve an action i've revoked the approval

**To Reproduce**

First as a BOD member i call pause the bank contract
By default as the caller my aprovement is automatic.
But in this BOD i'm the only one. So the transaction should be executed. 
Now i try to revoke my aprovement and do it again. 
I revok, it's working well 
But i can't approve aigain.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/b3d89789-bbc4-4119-9240-94278069071b)

**Comment by farrellh1** [comment]
can i make this won't fix, because the issue because you changed the wallet @hermannleboss
