### ISSUE TITLE
Unable to add a new member

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#376]
## Description

**Describe the bug**
Unable to add a new member

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/e4da46ed-cb80-4508-b98f-4fcd03a36fe7)

**Comment by hermannleboss** [comment]
This occur when the user don't have a name

**Comment by farrellh1** [comment]
<img width="488" alt="image" src="https://github.com/user-attachments/assets/fe6c0a1e-a582-488a-8f8c-ad770e963363">
