### ISSUE TITLE
feat: backend error handleing

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#42]
We should not return the error object when an error occure in the backend. 
If it's un handed error, we juste return an error message like "An error occured, please try aigian laitter" For 500 error. 
![image](https://github.com/globe-and-citizen/cnc-portal/assets/28951070/49196cca-1155-4047-ae7d-6f9c32313799)

It's because error can leak information about our architecture or code source. 

And about the errorResponse i think we should be able to use a custom message for it. 
`export const errorResponse = (code: number, error: any, res: Response) => {
...
}`

https://github.com/globe-and-citizen/cnc-portal/blob/b41d655115dda36f8ac490ba5212c91ece54c3eb/backend/src/utils/utils.ts#L3

**Comment by aliassan** [comment]
> We should not return the error object when an error occure in the backend. If it's un handed error, we juste return an error message like "An error occured, please try aigian laitter" For 500 error. ![image](https://private-user-images.githubusercontent.com/28951070/323256485-49196cca-1155-4047-ae7d-6f9c32313799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjI4NDksIm5iZiI6MTcxMzQyMjU0OSwicGF0aCI6Ii8yODk1MTA3MC8zMjMyNTY0ODUtNDkxOTZjY2EtMTE1NS00MDQ3LWFlN2QtNmY5YzMyMzEzNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA2NDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZmVkODg0NjU0N2IyZWM3M2QzMDA2OGY0ZDNhODAyNDMwMmZiZTM4NzdlMWYzNGY4NmE4OGMxYTc0ODEyNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ekMXD9AWpl_ip29TRQmcdExH67aeVNxslq65PA9Xwzo)
> 
> It's because error can leak information about our architecture or code source.
> 
> And about the errorResponse i think we should be able to use a custom message for it. `export const errorResponse = (code: number, error: any, res: Response) => { ... }`
> 
> https://github.com/globe-and-citizen/cnc-portal/blob/b41d655115dda36f8ac490ba5212c91ece54c3eb/backend/src/utils/utils.ts#L3

Yeah, the logic is there just it wasn't checking for status code. Will update it to check for status code as well

**Comment by aliassan** [comment]
But don't you think this kind of error handling is useful in development? We can remove it in production but in development I thought it would help to debug quicker.

**Comment by hermannleboss** [comment]
@aliassan you can log the error, so it's appears in the log of the backend but not in the response.
You can also display the stack trace in the log.

And make a condition to display the log in dev mode only.
