### ISSUE TITLE
[Feature] Investor Contract

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#431]
## Description

The investor contract is a stock management system for the company.

## Investor Contract expected feature

- Owner Initiate the contract, with initial supply, and inital SHER repartition.
- Owner can mint share for the employee every week
- Depending on the amount of SHER a user have, he can have dividend in the company. The dividend is calculated on the total amount of SHER the user have.

## User Story

**As** the owner of the investor contract,
**I want** to Create the investor contract and initiate the contract with the initial supply and initial SHER repartition.
**Then** the contract is created with the initial supply and initial SHER repartition.

**I want** to Mint share for the employee every week.
**Then** the share are minted and employee balance is updated.

For the investor contract function
- mintSHERTokens (amount: uint, shareholder: Address) // This min SHER for one address
- bashMint(CustomMaping: list[]) // This mint SHER for a list of address

Use mintSHERTokens to mint share for the employee when they sign the contract
Use bashMint to mint share for the employee every week

For the moment, mintSHERTokens, bashMint will be call by the owner, not available by an external contract

As an employ what i would like on the investor interface

- Get my balance
- Have the total suply
- List all owner of the company
- Stok Price
- Transfer SHER
- Contract Address

As the owner what i would like on the investor interface

- Button to mint share for the employee: Distribute SHARE
- Button to pay dividend
- Button to min token for a specific user
- Section to manage stock grant
  - For each stock grant type
    - Button to create a stock grant
    - List of all stock grant
    - Button to delete a stock grant
    - Button to update a stock grant

## Acceptance Criteria

- [x] Owner can initiate the investor contract by setting inital state of SHER share
- [x] Owner can mint token for one address
- [x] Owner can mint token for a list of address
- [x] Owner can mint token for employee ()

**Comment by farrellh1** [comment]
1. When initiating we can set the initial supply and initial distribution?
2. SHER transfer is ERC20 transfer? or mint new token?
3. How are IPO works in this contract?

and about the escrow contract, who's responsible to work on it?

here is some of questions from me @hermannleboss

**Comment by hermannleboss** [comment]
For the moment, we just have to do the user Stories. 
1- The initial distribution is to set funder Part. It's optional.
Ex: Farel Have 1000 SHER, and Hermann Have 300 SHER and Dasarah Have 100 SHER. 

2. SHER transfer is ERC20 Transfer, but all related is for the future. No need to wory about it now
3. IPO, is just a way to allow people to get SHER by buying them.
