### ISSUE TITLE
[Bug] issue When setting wage

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#455]
## Description

**Describe the bug**
When setting the member wage, the modal should close after the user submit the wage. 
The user submit the wage, but the hourly rate do not appear in the database 

**To Reproduce**

1. Create a team
2. Do no deploy any contract
3. Click on set wage
4. Submit your wage
5. There the modal do not close
6. And the db do update well

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/00c9e4ae-40df-4f88-a9ab-27a4c426932c)
![Image](https://github.com/user-attachments/assets/87ac570b-439e-46be-9360-3cc217cc6636)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aliassan** [comment]
I suppose it has to do with the data type, will need to update the contract and the schema
