### ISSUE TITLE
perf: metamask request to sign into the app at the loading

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/cnc-portal#78]
### Acceptance criteria

- [ ] Metamask Pop up should appear only when the user click on SIWE button.

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by dasarathg68** [comment]
#75
